### ISSUE TITLE
[Feature Request] Better Sort Order for MultiRow Toolbar

### ISSUE THREAD

**Issue by SlRvb** [phibr0/obsidian-advanced-toolbar#11]
I'd like to use the toolbar with a higher row count, but the order the toolbar displays my icons is somewhat unusable for me. Trying to sort the mobile toolbar to account for that manually would be a nightmare.

If you could calculate the total amount of icons/commands then split that into rows are so that it would order them in the original order, it would be fantastic for using the plugin with multiple rows.

# Example of the issue:
![IMG_2896|200](https://user-images.githubusercontent.com/54087190/137547869-16de98da-3ab0-4a5a-a9ce-c014e3a5cc70.jpg)

# Sort order that works in the original 1 line toolbar:
![IMG_2897](https://user-images.githubusercontent.com/54087190/137547912-d638ab2a-8ee0-4fe0-9c76-4f7ad5989f19.jpg)

**Comment by phibr0** [comment]
The Problem is that I don't actually rearrange the Icons in some way. I am just setting the height and using `display: flex`.
The flex direction is set as column, because otherwise it wouldn't wrap. Meaning the Buttons would just go on forever to the right.

I already have feature request for allowing someone to long press to rearrange the toolbar which should fix this too right?

**Comment by SlRvb** [comment]
Ooh I see, I fiddled a little bit with the css and I think I "fixed it". It just scrolls down now instead of sideways 🤣

```css
body.AT-multirow .mobile-toolbar-options-container { flex-flow: row wrap; }
.mobile-toolbar-options-container { overflow-y: auto; }
```
<img src="https://user-images.githubusercontent.com/54087190/137593761-8538ec22-d246-40f3-98f7-e60f3fb53862.gif" width="200" height="350">

---

Not sure if that's something that can or eve should be added as a toggle with a note about the vertical scroll, but if you decide not to go with this, feel free to close this issue 👍🏽

**Comment by melsophos** [comment]
I think that @SlRvb should be the default behavior because it makes much more sense.
