### ISSUE TITLE
Feature request - button width

### ISSUE THREAD

**Issue by breta999** [phibr0/obsidian-advanced-toolbar#13]
I would like the adjustable button width, or the button width could be the same as height row.

**Comment by breta999** [comment]
I tested the button width settings on both the mobile and the tablet and the width remains the same even after changing the settings.

**Comment by phibr0** [comment]
Are you using a theme?

**Comment by breta999** [comment]
I use the theme of red graphite, which I have significantly modified.  I have now tried several other theme and there is the same problem with the width of the button everywhere

**Comment by phibr0** [comment]
![image](https://user-images.githubusercontent.com/59741989/147392675-a9c3c395-60f2-4a7a-9395-efcafeae4800.png) *48px*

![image](https://user-images.githubusercontent.com/59741989/147392680-a9650115-7f13-4ce7-9136-3a54af17536d.png) *96px*

It should be working fine with default and minimal
Please try one of those themes and disable snippets if you have some enabled.

**Comment by breta999** [comment]
Larger values ​​work, but I would like the button width to be smaller, about 24 or 36 px

**Comment by breta999** [comment]
button resizing works, but button settings are not loaded from the mobile toolbar if I add, remove, or reorder buttons

**Comment by phibr0** [comment]
Hm, I don't quite understand what you mean by that.

**Comment by breta999** [comment]
I tested it again and everything works. Apparently I misunderstood the layout column settings. Thank you. Great job
