### ISSUE TITLE
Feature Request: Add class to body for better css styling

### ISSUE THREAD

**Issue by jdanielmourao** [phibr0/obsidian-advanced-toolbar#17]
Hi!
Some themes, such as my Sanctum, have floating buttons which can sometimes be hidden by the toolbar. One could simply change the positioning of the button in order for it not be hidden by the toolbar, but it would look strange for users not using the plugin.
Thus, I suggest adding a class to `body`, so theme developers and CSS snippet enthusiasts can change the button's position based on whether the plugin is on or off.

**Comment by phibr0** [comment]
Added in [1.7.3](https://github.com/phibr0/obsidian-advanced-toolbar/releases/tag/1.7.3). More details in the readme.

**Comment by phibr0** [comment]
Great Theme btw!
