### ISSUE TITLE
Ability to add items to tool bar

### ISSUE THREAD

**Issue by davebhc71** [phibr0/obsidian-advanced-toolbar#19]
I have not been able to add or rearrange items in the toolbar. Wasn’t this a feature of the plugin? Has something changed with the app updates? I’m using iPad with latest Insider release.
![IMG_0539](https://user-images.githubusercontent.com/80698092/150530171-c74cd3b7-8736-4a67-a38a-46f717d14f0e.jpeg)

**Comment by phibr0** [comment]
Adding and rearranging can be done in the toolbars native settings. This plugin just builds on top and adds some features. You should be able to find it in the default settings.

**Comment by davebhc71** [comment]
Of course! Getting toooooo old. THANK YOU!!!!
