### ISSUE TITLE
fail to load the plugin

### ISSUE THREAD

**Issue by kngautham** [phibr0/obsidian-advanced-toolbar#20]
i keep getting the message fail to load the plugin when I start the app

but the toolbar seems to be working. not sure if this is a bug

using Android app

**Comment by the0s0ph1st** [comment]
Just recently had the bug as well.

**Comment by phibr0** [comment]
Which Obsidian Version are you on?

**Comment by kngautham** [comment]
Current Version 1.0.5

**Comment by phibr0** [comment]
Thats weird... I cannot reproduce this Issue (or #21) on my Phone (Android) or the Desktop Version with emulated mobile mode.

**Comment by phibr0** [comment]
Version 1.0.5 was released two months ago so and it worked fine at that time. I have the current Insider build (1.0.10) on my phone in which it also works fine. Could you please test it with other plugins disabled or maybe in a freshly created vault?

**Comment by kngautham** [comment]
SInce your latest update, it is not loading. Before this recent update, i used to get the failed to load message, but the tollbar was showing and working,, but after the update, Plugin is completed not working

**Comment by phibr0** [comment]
> Could you please test it with other plugins disabled or maybe in a freshly created vault?

This fixed some issues for another user.

**Comment by kngautham** [comment]
I actually uninstalled and reinstalled and its working now. I should have tried this before raising the Issue. Sorry for that. In the meantime, can you look into giving us an option to see this toolbar inside Windows 10 App as well
