### ISSUE TITLE
Plugin seems to be broken with latest Obsidian update

### ISSUE THREAD

**Issue by davebhc71** [phibr0/obsidian-advanced-toolbar#24]
Current Obsidian Mobile seems to break the plugin. I’m using the Minimal Theme on an iPad. I need to keep uninstalling the Plugin and then reinstalling to see all the options. Then if I add a ‘command’ and/or change the icon, the Advanced Settings disappears until I uninstall and reinstall, AGAIN!

**Previously-**

![IMG_0637](https://user-images.githubusercontent.com/80698092/154857791-a8614bbc-c8dc-4197-b646-ab40ebdf2b65.jpeg)

**Now-** when I add an icon to a newly added option the Advanced Settings disappears.

![IMG_0638](https://user-images.githubusercontent.com/80698092/154857823-b5c7fc6e-952c-4eec-bb04-8f5f27e3b82a.jpeg)

**Comment by davebhc71** [comment]
HELLO…IS ANYONE HOME!

**Comment by phibr0** [comment]
Can you share the Debug Information? (Use the Debug Information Command from the Command Palette)

I cannot reproduce this Issue on any of my devices.

**Comment by davebhc71** [comment]
Here you go!

SYSTEM INFO:
	Operating system: ios 15.3.1 (Apple iPad)
	Login status: logged in
	Catalyst license: vip
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 28
	Plugins enabled: 21
		1: Advanced Tables
		2: Calendar
		3: Hotkeys for templates
		4: Lumberjack 🪓 🪵
		5: Natural Language Dates
		6: QuickAdd
		7: Templater
		8: Style Settings
		9: Obsidian TODO | Text-based GTD
		10: Contextual Typography
		11: Minimal Theme Settings
		12: Obsidian42 - BRAT
		13: Shortcut Launcher
		14: Advanced URI
		15: Customizable Sidebar
		16: Hider
		17: Obsidian42 - Jump-to-Date
		18: Paste URL into selection
		19: Customizable Page Header
		20: Hotkey Helper
		21: Advanced Mobile Toolbar

RECOMMENDATIONS:
	Update installer: installer version too low, please download from https://obsidian.md/download and reinstall.
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by davebhc71** [comment]
See image below-
1. Updated from TestFlight to latest App Store release - no difference
2. Minimal Theme is updated to latest version
3. Plugins are also updated to latest versions.
4. (Not shown) I’ve turned off all but Mobile Toolbar plugin, but issue remains.

Dave B

**Comment by davebhc71** [comment]
As I also posted in #23, you may want to have a look at this post in the Community Forum-
https://discord.com/channels/686053708261228577/864046194195431425/946333340817059870

**Comment by davebhc71** [comment]
👍

**Comment by davebhc71** [comment]
Same issue reappears with newest version update!!!

![IMG_0903](https://user-images.githubusercontent.com/80698092/161348144-051b5d1f-116b-493b-a1b7-3ca32c92d675.jpeg)
