### ISSUE TITLE
Toolbar (always visible) is overlapping sidebars 

### ISSUE THREAD

**Issue by MartinMiksch** [phibr0/obsidian-advanced-toolbar#25]
I can't see all the entries in the sidebars because of the toolbar. Would be great if this gets fixed.

![Screenshot_20220224-232903_Obsidian.jpg](https://user-images.githubusercontent.com/41252070/155687834-51723442-be3f-4d64-b293-af6dc1ec85d7.jpg)

**Comment by phibr0** [comment]
That seems to be a Issue with the Theme you are using. The toolbar should stay behind those drawers.

```css
.workspace-drawer {
    z-index: 10;
}
```

Please try adding this as a snippet

**Comment by MartinMiksch** [comment]
I played around a bit because of this information.

I'm using the Minimal theme. Unfortunately, the snippet didn't change anything. 

When I change to the default theme, the toolbar is also shown while opening the sidebars but I still can scroll through all entries. 

This isn't possible with the Minimal theme. Only when I pin the sidebar. So, the problem is with the theme but for now this works for me. 

Nevertheless, it would be great when the full sidebar could be shown over the toolbar. This isn't working for me neither with Minimal nor with the default theme.

**Comment by phibr0** [comment]
I am currently not able to push a full fix for this, but can you try the following snippet?

```css
.is-mobile .mobile-toolbar {
  position: absolute;
}
```

**Comment by MartinMiksch** [comment]
> I am currently not able to push a full fix for this, but can you try the following snippet?
> 
> ```css
> .is-mobile .mobile-toolbar {
>   position: absolute;
> }
> ```

This snippet works. 😀 Thx, for the quick fix! 🙏
