### ISSUE TITLE
latest release 1.21 build 52 - 2 rows does not wrap

### ISSUE THREAD

**Issue by adxsoft** [phibr0/obsidian-advanced-toolbar#27]
I have a two row configuration which worked perfectly on my Android mobile on last obsidian release. Latest obsidian mobile release shows two row area but the icons only occupy the first row and is horizontally scrollable.
Workarounds
- adjust icon spacing in plugin's advanced settings which seems to fix the problem
- is use one row or column mode.

**Comment by efemkay** [comment]
Yeah i had the same issue. But adjusting the spacing solved it

![Screenshot_20220412-064944_Obsidian](https://user-images.githubusercontent.com/42369515/162846679-58359412-ca81-4fcd-b45d-b112220516d2.jpg)

**Comment by phibr0** [comment]
Are you using a Theme? If so you might need to adjust the spacing in the advanced section. The Plugin is optimized to work best with the default theme.

**Comment by adxsoft** [comment]
Yes I am using a theme. Adjusting the spacing worked perfectly thanks. I
think the spacing seeing I had before upgrading the mobile app was somehow
reset.
Cheers

**Comment by phibr0** [comment]
Okay
