### ISSUE TITLE
Toolbar partially hidden on iPadOS

### ISSUE THREAD

**Issue by davebhc71** [phibr0/obsidian-advanced-toolbar#30]
Please note from the screen shots below that a segment (left most items) of the Toolbar become hidden behind the Left Panel when it (Pane/Panel) is pinned to the screen. Toolbar does slide to the right but does NOT stay in position to view or select items.
![IMG_0012](https://user-images.githubusercontent.com/80698092/163672644-de3a9970-99c5-4053-9b70-d3b53b82e0fb.jpeg)

![IMG_0011](https://user-images.githubusercontent.com/80698092/163672657-d16b1a4d-3d98-47ae-97ee-96de746791c8.jpeg)

**Comment by phibr0** [comment]
Does the new update fix the Issue?

**Comment by davebhc71** [comment]
Fixed!!! Thanks for the fast work!

**Comment by davebhc71** [comment]
Sure does! Thanks, left response in Git too.
Dave B

**Comment by kunicki** [comment]
Thank you for this fix. Was just noticing it yesterday on iPad, and I am making more use of mobile toolbar.

Tnx!

**Comment by davebhc71** [comment]
Issue (toolbar partially obscured by Apple black bar) has reappeared with the latest Insider-Mobile v1.6 release. Is it possible to add a control for extending the night of the ‘bar’ without splitting the icons into 2.3 or 4 rows?
![5C8AB966-DDD0-48F9-A8C4-FA82D790478B](https://user-images.githubusercontent.com/80698092/193405879-f8502a3f-0a44-4c6b-be2d-6e9860150567.jpeg)
