### ISSUE TITLE
Showing tooltips

### ISSUE THREAD

**Issue by trungng2006** [phibr0/obsidian-advanced-toolbar#4]
When i use my note8, hovering the pen on any icon in obsidian would show tooltip. However, tooltip does not show up on toolbar. 
Would it be possible if you could add this function please?

**Comment by phibr0** [comment]
It actually is pretty doable. Will work on this later this week

**Comment by trungng2006** [comment]
Thank you so much!

**Comment by phibr0** [comment]
There is now a option in the Settings to enable tooltips!
