### ISSUE TITLE
Toolbar not showing up in preview mode sometimes

### ISSUE THREAD

**Issue by AngelusDomini** [phibr0/obsidian-advanced-toolbar#5]
I've set the Always Show Toolbar option on, but the toolbar doesn't show in preview mode at certain times.

I've noticed at startup, when the open note is in preview mode, the toolbar doesn't show, even though it shows if the open note is in edit mode.

After typing in edit mode and then switching to preview without hiding the on-screen keyboard, the toolbar disappears.

It's only when I switch from preview to edit to preview again (with the on-screen keyboard hidden) does the toolbar show up. I initially thought the Always Show Toolbar setting didn't include preview mode until I accidentally discovered how I could get it to show up in preview.

**Comment by phibr0** [comment]
Should be fixed, could you update and try again?

**Comment by AngelusDomini** [comment]
Yep! So far so good. Thanks so much!
