### ISSUE TITLE
bug: changing the advanced setting "Button height" does not work

### ISSUE THREAD

**Issue by mcndt** [phibr0/obsidian-advanced-toolbar#6]
When I try to change this value, after closing the settings modal the value is automatically reset to 48.

**Comment by phibr0** [comment]
What did you write into it? If you don't use numbers only it gets reset

**Comment by mcndt** [comment]
I'm trying to set it to 32.

**Comment by phibr0** [comment]
There was indeed a small Bug, should be fixed in the newest Version

**Comment by mcndt** [comment]
Quick fix, thx!
