### ISSUE TITLE
[Feature] To turn off permanent display when external keyboard is connected

### ISSUE THREAD

**Issue by dummifiedme** [phibr0/obsidian-advanced-toolbar#7]
Currently, the bar is displayed permanently if the option is turned on (which is useful when using without a keyboard), but once the keyboard is connected, it loses it’s utility. Can this be automatically turned off once a keyboard is connected? (IPad or Android)

**Comment by phibr0** [comment]
You can set the Row Count to 0 which will make the Toolbar disappear. Currently there is no way for a Plugin to know if a Keyboard is connected though.

**Comment by dummifiedme** [comment]
> You can set the Row Count to 0 which will make the Toolbar disappear. Currently there is no way for a Plugin to know if a Keyboard is connected though.

Ah, this is what I suspected :)

**Comment by phibr0** [comment]
Would Commands to toggle the Toolbar provide a workaround for you?

**Comment by dummifiedme** [comment]
> Would Commands to toggle the Toolbar provide a workaround for you?

I guess, yes.
